version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build: .
    container_name: qr-ticketing-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
